name: AdvancedItems
version: '${project.version}'
main: ru.moongl.minecraft.advanceditems.AdvancedItems
api-version: 1.19
authors: [ neverlessy, MoonGlance ]
description: Plugin for additional subject settings and built-in statistics.
website: https://moongl.ru

commands:
  adi:
    description: kavoha
    usage: /adi <menu/create/delete> <itemType/name>